In [1]:
# Basic
from collections import Counter
import math
import numpy as np
import os
import pprint

# yaml specific
import yaml

# Data handling
import pandas as pd
from tqdm import tqdm

In [2]:
# Config variables
raw_data_path = "raw_data"
clean_data_path = "clean_data"
tournament_name = "IPL"

## Utility functions. Move them to separate files later

In [3]:
def parse_yaml(path):
    """
    Parses a given yaml file and returns the object
    Args:
        path - path of the yaml file to be parsed
    """
    with open(path, 'r') as stream:
        try:
            data = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)
    return data

In [4]:
def get_all_matches_raw_data(tournament_name):
    tournament_path = os.path.join(raw_data_path, tournament_name)
    match_files = os.listdir(tournament_path)
    matches = []
    print(f"Parsing {len(match_files)} matches for {tournament_name}")
    for match_file in tqdm(match_files):
        match_path = os.path.join(tournament_path, match_file)
        match = parse_yaml(match_path)
        matches.append(match)
    return matches

In [5]:
def get_clean_teams(major_teams):
    # remove bad chars from string
    bad_chars = [';', ':', '!', "*", "'", '"', '[', ']', ',']
    teams = []
    for team in major_teams.split(", "):
        for char in bad_chars:
            team = team.replace(char, "")
        teams.append(team.strip().rstrip())
    return teams

# Defining tables
### Initially handling everything through CSVs. Later, we will see if using a DB is required

In [6]:
players = pd.read_csv("raw_data/players.csv")
players = players.loc[:, ~players.columns.str.contains('^Unnamed')]

C:\Users\aniru\miniconda3\envs\torch\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (101,107,108,140,141,145,146,147,153,154,158,159,160) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

## Country table

### Focusing only on the top 20 countries with professional cricket players

In [7]:
countries = []
for key, value in players["COUNTRY"].value_counts().nlargest(20).iteritems():
    print(f"{key} --> {value}")
    countries.append(key)

England --> 20908
India --> 13257
South Africa --> 10095
Australia --> 6921
Pakistan --> 6846
Sri Lanka --> 6079
New Zealand --> 3731
United Arab Emirates --> 3331
West Indies --> 3317
Bangladesh --> 1815
Afghanistan --> 1410
Zimbabwe --> 1237
Ireland --> 794
Scotland --> 663
United States of America --> 618
Netherlands --> 495
Malaysia --> 462
Canada --> 436
Hong Kong --> 428
Nepal --> 411

In [8]:
country_columns = ["country_id", "country_name"]
country_csv = pd.DataFrame(columns = country_columns)
for i in range(len(countries)):
    country_id = i+1
    country_name = countries[i]
    country_csv = country_csv.append({"country_id" : country_id, 
                                      "country_name" : country_name}, ignore_index=True)

In [9]:
country_csv

   country_id              country_name
0           1                   England
1           2                     India
2           3              South Africa
3           4                 Australia
4           5                  Pakistan
5           6                 Sri Lanka
6           7               New Zealand
7           8      United Arab Emirates
8           9               West Indies
9          10                Bangladesh
10         11               Afghanistan
11         12                  Zimbabwe
12         13                   Ireland
13         14                  Scotland
14         15  United States of America
15         16               Netherlands
16         17                  Malaysia
17         18                    Canada
18         19                 Hong Kong
19         20                     Nepal

In [10]:
country_csv.to_csv(os.path.join(clean_data_path, "country.csv"), index=False)

## Team table

### Considering only those teams where the players belong to the above 20 countries and aged < 50 (as of 2019)

In [11]:
required_columns = ['NAME', 'COUNTRY', 'Full name', 'Birthdate', 'Major teams', 'Batting style', 'Bowling style', 'Other']
required_players = players[(players["COUNTRY"].isin(countries)) & (players["Age"] < 50)][required_columns]

In [12]:
teams = []
for index, row in tqdm(required_players.iterrows()):
    #print(f'{row["NAME"]} -- > {row["Major teams"]}')
    # skip columns that are not string
    if type(row["Major teams"]) is not str:
        continue
    for team in get_clean_teams(row["Major teams"]):
        teams.append(team)

34016it [00:02, 15088.93it/s]

### If a team has less than 'threshold' registered professional players, ignore that team

In [13]:
threshold = 10
threshold_count = 0
teams_set = set()
for team, count in Counter(teams).most_common():
    if count > threshold:
        threshold_count += 1
        teams_set.add(team)

In [14]:
teams_list = list(teams_set)

In [15]:
team_columns = ["team_id", "team_name", "team_label"]
team_csv = pd.DataFrame(columns = team_columns)
for i in tqdm(range(len(teams_list))):
    team_id = i+1
    team_name = teams_list[i]
    team_label = "".join(word[0] for word in team_name.split(" "))
    team_csv = team_csv.append({"team_id" : team_id, 
                                "team_name" : team_name, 
                                "team_label" : team_label}, ignore_index=True)

100%|█████████████████████████████████████████████████████████████████████████████| 1216/1216 [00:02<00:00, 522.96it/s]

In [16]:
team_csv

     team_id                               team_name team_label
0          1                      Tasmania Under-17s         TU
1          2  Australian Capital Territory Under-23s       ACTU
2          3                         Assam Under-14s         AU
3          4                 Middlesex Cricket Board        MCB
4          5        Sri Lanka Cricket Development XI      SLCDX
...      ...                                     ...        ...
1211    1212                            Canterbury A         CA
1212    1213                      Karachi Port Trust        KPT
1213    1214                               Australia          A
1214    1215           Kurunegala Youth Cricket Club       KYCC
1215    1216                         Mid West Rhinos        MWR

[1216 rows x 3 columns]

In [17]:
team_csv.to_csv(os.path.join(clean_data_path, "team.csv"), index=False)

## Player table

### Considering only those players who belong to the 20 countries and aged < 50 (as of 2019)

### Utility maps to ingest players

In [19]:
df_country = pd.read_csv(os.path.join(clean_data_path, "country.csv"))
df_country = df_country.loc[:, ~df_country.columns.str.contains('^Unnamed')]
country_id_map = dict(zip(df_country.country_name, df_country.country_id))

In [20]:
df_team = pd.read_csv(os.path.join(clean_data_path, "team.csv"))
df_team = df_team.loc[:, ~df_team.columns.str.contains('^Unnamed')]
team_id_map = dict(zip(df_team.team_name, df_team.team_id))

In [21]:
team_id_map

{'Tasmania Under-17s': 1,
 'Australian Capital Territory Under-23s': 2,
 'Assam Under-14s': 3,
 'Middlesex Cricket Board': 4,
 'Sri Lanka Cricket Development XI': 5,
 'England Cricket Board XI': 6,
 'Takhar Province Under-16s': 7,
 'West Indies Women': 8,
 'Federally Administered Tribal Areas': 9,
 'Sapphires': 10,
 'Cricket Association of Bengal Under-17s': 11,
 'Andhra Under-14s': 12,
 'Jamaica Women': 13,
 'Kilinochchi Combined Schools': 14,
 'United Arab Emirates Women': 15,
 'Queensland Colts': 16,
 'Kaluthara Maha Vidyalaya': 17,
 'Andhra Women': 18,
 'Northerns': 19,
 'Northern Territory Under-19s': 20,
 'Sheikh Jamal Dhanmondi Club': 21,
 'Australia Under-21s Women': 22,
 'Eastern Province Under-19s': 23,
 'Panadura Sports Club': 24,
 'The Rest': 25,
 'Free State Under-13s': 26,
 'Pakistan Under-23s': 27,
 'Pakistan Under-15s': 28,
 'AMC Abbottabad': 29,
 'Sylhet Division': 30,
 'KwaZulu-Natal Under-13s': 31,
 'Surrey Cricket Board': 32,
 'Laghman Province Under-16s': 33,
 'United Bank Limited': 34,
 'Khulna Division Under-16s': 35,
 'Durham Academy': 36,
 'Hampshire': 37,
 'Mumbai Indians': 38,
 'Delhi Women': 39,
 'Vimukthi Cricket Club': 40,
 'Griqualand West Under-15s': 41,
 'South Australia': 42,
 'Leeds/Bradford MCCU': 43,
 'Surrey Under-13s': 44,
 'Northern Windward Islands': 45,
 'Manipur': 46,
 'United Arab Emirates': 47,
 'Brisbane Heat Women': 48,
 'Worcestershire Under-15s': 49,
 'Nottinghamshire Under-15s': 50,
 'Albert TUTI Patriots': 51,
 'Kent Under-13s': 52,
 'Europeans (India)': 53,
 'Lancashire Under-15s': 54,
 'Chittagong Division Under-14s': 55,
 'Bangladesh Women': 56,
 'New Zealand Women': 57,
 'Lancashire Under-17s': 58,
 'Islamabad United': 59,
 'Australian Capital Territory Under-15s Women': 60,
 'Pakistan Women': 61,
 'Boost Region': 62,
 'Badureliya Sports Club': 63,
 'Kerala': 64,
 'New South Wales Country': 65,
 'South Queensland Under-19s': 66,
 'Dorset Women': 67,
 'Service Industries': 68,
 'England Women': 69,
 'Hyderabad Under-14s': 70,
 'Hong Kong Cricket Association Under-19s': 71,
 'Puducherry': 72,
 'Jammu & Kashmir Under-16s': 73,
 'Wellington A': 74,
 'University of New South Wales': 75,
 'Queensland Under-15s Women': 76,
 'Sussex Cricket Board': 77,
 'Australia Under-16s': 78,
 'Bengal Under-16s': 79,
 'Rest of North West Frontier Province': 80,
 'Delhi Daredevils': 81,
 'Pakistan International Airlines': 82,
 'Auckland Under-21s Women': 83,
 'St. Benedicts College': 84,
 'Chittagong Division Under-16s': 85,
 'Pakistan Reserves': 86,
 'Lumbini Maha Vidyalaya': 87,
 'Northern Districts Women': 88,
 'Cambridgeshire': 89,
 'Natal': 90,
 'Kandy Cricket Club': 91,
 'India Under-19s': 92,
 'Kerala Under-16s': 93,
 'Montreal Tigers': 94,
 'British Universities': 95,
 'Khulna Royal Bengals': 96,
 'Worcestershire Women': 97,
 'Madhya Pradesh': 98,
 'Lions': 99,
 'Western Australia': 100,
 'Laghman Province': 101,
 'Menlopark High School': 102,
 'United States of America Under-15s': 103,
 'Parwan Province Under-16s': 104,
 'New Zealand A': 105,
 'Wesley College': 106,
 'AMCC Ajman': 107,
 'Combined Campuses and Colleges': 108,
 'Worcestershire': 109,
 'St. Anthonys College (Watthala)': 110,
 'Moratuwa Sports Club Women': 111,
 'Jammu & Kashmir': 112,
 'Palink Sports Club': 113,
 'Dhaka Metro Under-16s': 114,
 'Schools Invitation XI': 115,
 'India A Women': 116,
 'Zabul Province Under-16s': 117,
 'Shakthi Ladies': 118,
 'Transvaal': 119,
 'Sri Lanka Board Presidents XI': 120,
 'Hong Kong Cricket Club': 121,
 'South Western Districts Under-17s': 122,
 'Bengal': 123,
 'Saracens': 124,
 'Canterbury Under-21s Women': 125,
 'Delhi Giants': 126,
 'United States of America Under-19s': 127,
 'West Indies B': 128,
 'Belagavi Panthers': 129,
 'Sri Lanka A': 130,
 'Tasmania Under-23s': 131,
 'Tamil Nadu Under-19s': 132,
 'Allied Bank': 133,
 'Queensland Under-15s': 134,
 'Hobart Hurricanes': 135,
 'Leeward Islands Under-19s': 136,
 'Rizvi Mumbai': 137,
 'Kandyan Ladies Cricket Club': 138,
 'Australia Under-15s': 139,
 'Central Zone (Bangladesh)': 140,
 'Sui Southern Gas Corporation': 141,
 'Islamia College Sialkot': 142,
 'Guyana Amazon Warriors': 143,
 'Gloucestershire Cricket Board': 144,
 'Berkshire Women': 145,
 'Worcestershire Under-17s': 146,
 'KwaZulu-Natal Inland Under-13s': 147,
 'Malaysia Under-17s': 148,
 'Emerson College Multan': 149,
 'Bellary Tuskers': 150,
 'Orissa': 151,
 'Hong Kong Under-16s': 152,
 'Pakistan Automobiles Corporation': 153,
 'Limpopo': 154,
 'Kalutara Vidyalaya': 155,
 'Namibia Under-15s': 156,
 'Mashonaland Eagles': 157,
 'Punjab Women (India)': 158,
 'Victoria Under-15s': 159,
 'Sialkot Cricket Association': 160,
 'Essex Under-17s': 161,
 'Mumbai Champs': 162,
 'Tripura Under-14s': 163,
 'Lankan Cricket Club': 164,
 'South Australia Country': 165,
 'Gauteng Under-17s': 166,
 'Yorkshire Women': 167,
 'Karachi University': 168,
 'Mumbai Cricket Association Presidents XI': 169,
 'Warwickshire 2nd XI': 170,
 'Centaur Warriors': 171,
 'Canada Women': 172,
 'Australian Capital Territory Under-17s': 173,
 'Central Zone': 174,
 'Scotland Under-13s': 175,
 'Wales Women': 176,
 'Balkh Province Under-16s': 177,
 'Uttarakhand': 178,
 'Sri Lanka Army': 179,
 'Easterns Under-15s': 180,
 'South Africa Under-19s': 181,
 'Bangalore Brigadiers (Urban)': 182,
 'Dominica Women': 183,
 'Matabeleland': 184,
 'Ireland Under-15s': 185,
 'KwaZulu-Natal': 186,
 'Pakistan A': 187,
 'St. Thomas College': 188,
 'Dhaka Division South Under-18s': 189,
 'Delhi Under-14s': 190,
 'Western Province': 191,
 'Australia Under-19s': 192,
 'Gloucestershire': 193,
 'Essex': 194,
 'Moratuwa Sports Club': 195,
 'Norfolk': 196,
 'Pakistan Television': 197,
 'Montserrat': 198,
 'Warwickshire Under-14s': 199,
 'South Africa': 200,
 'Dhaka Division': 201,
 'Partex Sporting Club': 202,
 'Nevis': 203,
 'South Africa Women': 204,
 'Yorkshire Cricket Board': 205,
 'St Maarten': 206,
 'Polonnaruwa Combine Schools': 207,
 'Surrey 2nd XI': 208,
 'Grenada': 209,
 'Gauteng Under-19s': 210,
 'Border Women': 211,
 'Victoria Institute of Sport': 212,
 'Bahawalpur': 213,
 'London County': 214,
 'Hong Kong': 215,
 'Lanka Womens Cricket Club': 216,
 'Malaysia Under-19s': 217,
 'Griqualand West Under-19s': 218,
 'Western Australia Country': 219,
 'Cambridge MCCU': 220,
 'Hyderabad Hawks': 221,
 'Mpumalanga Under-17s': 222,
 'Shropshire Women': 223,
 'Kandurata Maroons': 224,
 'South Africa Blind': 225,
 'Khost Province Under-16s': 226,
 'Northern Territory Combined Under-15s': 227,
 'Richmond College': 228,
 'Durham Cricket Board': 229,
 'Krira Shikkha Protisthan Under-18s': 230,
 'Scotland Under-19s': 231,
 'Mizoram': 232,
 'Scotland': 233,
 'Trinco-Batti Combined Schools': 234,
 'Northerns Under-19s': 235,
 'Barbados': 236,
 'Ireland Women': 237,
 'Uttar Pradesh Under-14s': 238,
 'APS': 239,
 'Staffordshire Women': 240,
 'Madhya Pradesh Under-19s': 241,
 'Cornwall': 242,
 'Dhaka Metro Under-14s': 243,
 'Bangladesh Cricket Board Academy': 244,
 'Mohammedan Sporting Club': 245,
 'Asia Women XI': 246,
 'North West Under-17s': 247,
 'Gurugram Spartans': 248,
 'Universiti Kebangsaan Malaysia': 249,
 'New Zealand Under-19s': 250,
 'St Vincent and the Grenadines Women': 251,
 'Dharmashoka College': 252,
 'Border Under-17s': 253,
 'Nalanda College': 254,
 'Chittagong Division Under-18s': 255,
 'Amo Region Under-16s': 256,
 'Asia XI': 257,
 'Barbados Women': 258,
 'St Johns College': 259,
 'Zarai Taraqiati Bank Limited': 260,
 'Bangladesh A': 261,
 'Kings XI Punjab': 262,
 'Barbados Under-19s': 263,
 'Band-e-Amir Region': 264,
 'Bangladesh Under-17s': 265,
 'Madurai Super Giant': 266,
 'Zimbabwe Under-17s': 267,
 'Edmonton Royals': 268,
 'Sri Lanka Schools XI': 269,
 'England Academy Women': 270,
 'Jamaica': 271,
 'Somerset Under-14s': 272,
 'Sri Lanka Air Force Sports Club': 273,
 'Scotland Under-17s': 274,
 'Abbottabad Falcons': 275,
 'European University of Bangladesh': 276,
 'Quetta Gladiators': 277,
 'Kei': 278,
 'Khelaghar Samaj Kallyan Samity': 279,
 'LUMHS Hyderabad': 280,
 'Comsats Islamabad': 281,
 'Netherlands Women': 282,
 'Kingswood College (Kandy)': 283,
 'Hampshire Under-17s': 284,
 'Middlesex 2nd XI': 285,
 'Chittagong Kings': 286,
 'Dhaka Division South Under-14s': 287,
 'Orissa Cricket Association XI': 288,
 'India Green': 289,
 'Vidarbha Cricket Association XI': 290,
 'Tamil Nadu': 291,
 'Eastern Province Under-17s': 292,
 'North West Under-15s': 293,
 'Baroda': 294,
 'Zimbabwe Under-13s': 295,
 'Dominica': 296,
 'North Central Province Women': 297,
 'Rangpur Division Under-14s': 298,
 'Kandahar Province Under-16s': 299,
 'Jaipur Jaguars': 300,
 'Karachi Harbour': 301,
 'Scotland A': 302,
 'Cambridge Town Club': 303,
 'Sri Lanka Under-23s': 304,
 'Jammu & Kashmir Under-14s': 305,
 'Rangpur Division': 306,
 'West Indies': 307,
 'Gujarat': 308,
 'Public Works Department': 309,
 'Services': 310,
 'Malnad Gladiators': 311,
 'Rajasthan Under-19s': 312,
 'United States of America': 313,
 'Easterns': 314,
 'Adelaide Strikers Women': 315,
 'Pakistan University Grants Commission': 316,
 'Kochi Tuskers Kerala': 317,
 'Kent Under-15s': 318,
 'Rajshahi Division': 319,
 'Islamabad': 320,
 'Old DOHS Sports Club': 321,
 'Rawalpindi Rams': 322,
 'Mpumalanga': 323,
 'Kerala Under-14s': 324,
 'Sileby Town Ladies CC': 325,
 'Northerns (Zimbabwe)': 326,
 'North Queensland': 327,
 'Logar Province Under-16s': 328,
 'Uttar Pradesh': 329,
 'Sussex': 330,
 'Ireland A': 331,
 'Derbyshire Women': 332,
 'Malaysia': 333,
 'Prime Ministers XI': 334,
 'Dhaka Division North Under-16s': 335,
 'Sunrisers Hyderabad': 336,
 'Kandy Youth Cricket Club': 337,
 'India Green Women': 338,
 'Assam Under-16s': 339,
 'Vidarbha Under-19s': 340,
 'Kalutara Physical Culture Club': 341,
 'Australian Country XI': 342,
 'Sarawak': 343,
 'Multan Region': 344,
 'Orange Free State': 345,
 'Worcestershire Under-14s': 346,
 'Derbyshire Under-13s': 347,
 'Islamia College Peshawar': 348,
 'KwaZulu-Natal Under-17s': 349,
 'Southerns': 350,
 'Loughborough MCCU': 351,
 'Matabeleland Tuskers': 352,
 'Hong Kong Under-19s': 353,
 'Dhaka Metropolis': 354,
 'Basnahira South': 355,
 'Easterns (Zimbabwe)': 356,
 'Dehradun Devils': 357,
 'Bahawalpur Stags': 358,
 'Colombo Cricket Club': 359,
 'Tamil Nadu Under-14s': 360,
 'Malaysian Armed Forces': 361,
 'Maharashtra Under-22s': 362,
 'Bihar Under-16s': 363,
 'New Zealand XI': 364,
 'Jaffna Central College': 365,
 'Railways (India) Women': 366,
 'Nottinghamshire Under-13s': 367,
 'Central East Region': 368,
 'Khan Research Labs': 369,
 'South Western Districts Women': 370,
 'The Champs': 371,
 'Mumbai Cricket Association XI': 372,
 'Himachal Pradesh Under-19s': 373,
 'Mis Ainak Region': 374,
 'Western Australia Under-15s': 375,
 'North West Under-19s': 376,
 'Auckland': 377,
 'Philadelphians': 378,
 'Unicorns A': 379,
 'Leicestershire Women': 380,
 'British Virgin Islands': 381,
 'Basnahira North': 382,
 'Sialkot': 383,
 'Karnataka Women': 384,
 'Queensland Under-23s': 385,
 'Queensland Academy of Sport': 386,
 'Railways': 387,
 'New South Wales Under-17s': 388,
 'Palink School of Cricket': 389,
 'Essex Cricket Board': 390,
 'Bengal Women': 391,
 'Surrey Women': 392,
 'Northern Cape Under-13s': 393,
 'Herat Province Under-16s': 394,
 'University of Moratuwa': 395,
 'Rajshahi Division Under-16s': 396,
 'Gujarat Cricket Association XI': 397,
 'Brothers Union': 398,
 'Barisal Division Under-18s': 399,
 'Stanford Superstars': 400,
 'Cumberland': 401,
 'Pakistan Under-16s': 402,
 'Barisal Division Under-14s': 403,
 'North West Under-13s': 404,
 'Northern Districts Under-19s': 405,
 'Peshawar Cricket Association': 406,
 'Otago A': 407,
 'Sylhet Divison Under-14s': 408,
 'Lahore Eagles': 409,
 'East Zone (Bangladesh)': 410,
 'East Zone Women': 411,
 'VRA Cricket': 412,
 'Ananda College': 413,
 'Kowloon Cricket Club': 414,
 'Badulla & Monaragala Combine Schools': 415,
 'Afghanistan A': 416,
 'Central Districts': 417,
 'Devon Women': 418,
 'Maharashtra Under-19s': 419,
 'Sylhet Divison Under-16s': 420,
 'Karandeniya Central College': 421,
 'Maharashtra Women': 422,
 'Western Province Boland': 423,
 'University of Free State': 424,
 'England Development Squad Women': 425,
 'Redco Pakistan Ltd': 426,
 'Rangpur Division Under-16s': 427,
 'Western Australia Under-17s': 428,
 'Vancouver Knights': 429,
 'Hyderabad (India)': 430,
 'Barisal Burners': 431,
 'Rest of Sindh': 432,
 'Oxford MCCU': 433,
 'Shamanoor Davangere Diamonds': 434,
 'Baroda Under-16s': 435,
 'Queensland Women': 436,
 'Netherlands Under-13s': 437,
 'Durham Women': 438,
 'Impi': 439,
 'Pakistan Railways': 440,
 'Warwickshire Cricket Board': 441,
 'Perth Scorchers': 442,
 'Hampshire 2nd XI': 443,
 'England A': 444,
 'Rajasthan Royals': 445,
 'Saurashtra Women': 446,
 'Ireland': 447,
 'Agriculture Development Bank of Pakistan': 448,
 'Eastern Province Under-13s': 449,
 'Wiltshire': 450,
 'Netherlands Under-15s': 451,
 'Northumberland': 452,
 'Quetta': 453,
 'Eastern Province Women': 454,
 'Ireland Under-13s': 455,
 'Faisalabad': 456,
 'Sebastianites Cricket and Athletic Club': 457,
 'Nottinghamshire Cricket Board': 458,
 'Middlesex Under-15s': 459,
 'S.Thomas College': 460,
 'Punjab College Bahawalpur': 461,
 'FOG-Seenigama Ladies': 462,
 'Mumbai Under-19s': 463,
 'Sports College Lucknow': 464,
 'Sikkim Under-16s': 465,
 'St Lucia Zouks': 466,
 'Sri Lanka Women': 467,
 'Canterbury': 468,
 'Northern Districts A': 469,
 'Trinidad & Tobago Under-19s': 470,
 'Delhi Kings': 471,
 'Derbyshire 2nd XI': 472,
 'Andhra Under-19s': 473,
 'Victoria Women': 474,
 'Victoria Sporting Club': 475,
 'Somerset Under-15s': 476,
 'Odisha Women': 477,
 'Dindigul Dragons': 478,
 'Afghanistan Under-19s': 479,
 'Haryana Under-16s': 480,
 'St Kitts and Nevis Patriots': 481,
 'Speen Ghar Region': 482,
 'Ahmedabad Rockets': 483,
 'Sri Lanka Blind': 484,
 'Hoer Volkskool': 485,
 'Border': 486,
 'Dhaka Gladiators': 487,
 'Surrey Under-15s': 488,
 'Lancashire Women': 489,
 'St Kitts': 490,
 'Islamabad Cricket Association': 491,
 'Baluchistan': 492,
 'Chennai Superstars': 493,
 'Boland Under-13s': 494,
 'Amo Region': 495,
 'South Zone (Bangladesh)': 496,
 'Rangpur Division Under-18s': 497,
 'KwaZulu-Natal Women': 498,
 'Gujarat Lions': 499,
 'Lyca Kovai Kings': 500,
 'West Indies Under-15s': 501,
 'Sri Lanka Cricket Combined Women': 502,
 'Antonians Sports Club': 503,
 'Berkshire': 504,
 'South Zone': 505,
 'St Vincent': 506,
 'Glamorgan': 507,
 'Gloucestershire 2nd XI': 508,
 'Windward Islands': 509,
 'Kolkata Knight Riders': 510,
 'Up Country Combined Schools': 511,
 'Moors Sports Club': 512,
 'Middlesex Under-17s': 513,
 'Nottinghamshire': 514,
 'Northamptonshire 2nd XI': 515,
 'Chennai Super Kings': 516,
 'Scotland Women': 517,
 'Nottinghamshire Under-14s': 518,
 'Wales Minor Counties': 519,
 'Assam': 520,
 'Somerset Cricket Board': 521,
 'Seeduwa Raddoluwa Cricket Club': 522,
 'South Western Districts Under-19s': 523,
 'Jamaica Tallawahs': 524,
 'South Africa Emerging Players': 525,
 'Melbourne Cricket Club': 526,
 'Guyana Women': 527,
 'Victoria Under-23s': 528,
 'S.Thomas College Bandarawela': 529,
 'Derbyshire': 530,
 'Sui Gas Corporation of Pakistan': 531,
 'Northamptonshire Cricket Board': 532,
 'Lahore Qalandars': 533,
 'Gauteng': 534,
 'Berkshire Under-15s': 535,
 'Canterbury Under-17s': 536,
 'Limpopo Under-15s': 537,
 'Jammu & Kashmir Under-19s': 538,
 'Framesby High School': 539,
 'University of West Indies': 540,
 'Rising Pune Supergiants': 541,
 'Nottinghamshire 2nd XI': 542,
 'Krira Shikkha Protisthan Under-14s': 543,
 'Devon': 544,
 'North Zone': 545,
 'Western Province Under-13s': 546,
 'Maidan Wardak Province Under-16s': 547,
 'Oxford University Women': 548,
 'Chandigarh Cheetaas': 549,
 'Rajshahi Kings': 550,
 'Africa XI': 551,
 'Cricket Coaching School': 552,
 'Khan Research Laboratories': 553,
 'Kerala Under-19s': 554,
 'Dhaka Division North Under-14s': 555,
 'Northamptonshire': 556,
 'South Africa Academy': 557,
 'Tasmania Under-19s': 558,
 'North Zone (Bangladesh)': 559,
 'India Disable': 560,
 'Sui Northern Gas Pipelines Limited': 561,
 'Butt XI': 562,
 'Ruby Trichy Warriors': 563,
 'Pakistan Customs': 564,
 'Derbyshire Under-15s': 565,
 'Himachal Pradesh Under-16s': 566,
 'Essex 2nd XI': 567,
 'Mountaineers': 568,
 'Australian Capital Territory Under-19s': 569,
 'Derbyshire Under-17s': 570,
 'Hertfordshire': 571,
 'Saurashtra Under-19s': 572,
 'Gauteng Women': 573,
 'Charlbury Women CC': 574,
 'Western Province Women': 575,
 'Andhra Under-25s': 576,
 'P De S Kularatne College': 577,
 'Haryana Under-19s': 578,
 'Marwari College Ranchi': 579,
 'Punjab Under-14s': 580,
 'Zimbabwe A': 581,
 'Narammala Sports Club Women': 582,
 'KwaZulu-Natal Under-19s': 583,
 'St. Sebastians College Katuneriya': 584,
 'Nottinghamshire Women': 585,
 'Government College Murree': 586,
 'Auckland Under-19s': 587,
 'Quetta Bears': 588,
 'Trinidad & Tobago': 589,
 'Leicestershire 2nd XI': 590,
 'Western Australia Women': 591,
 'Mumbai Under-16s': 592,
 'Sydney Sixers': 593,
 'Punjab': 594,
 'De Mazenod College': 595,
 'Peshawar Panthers': 596,
 'Southern Windward Islands': 597,
 'Cambridge University': 598,
 'Victoria': 599,
 'Wayamba': 600,
 'Nepal Under-17s': 601,
 'Winnipeg Hawks': 602,
 'India Under-21s Women': 603,
 'Suffolk Under-13s': 604,
 'Middlesex': 605,
 'Middlesex Under-19s': 606,
 'Western Province Under-15s': 607,
 'Sri Lanka Academy XI': 608,
 'Queensland Under-19s': 609,
 'Lancashire': 610,
 'Somerset Women': 611,
 'Kent Under-17s': 612,
 'Malaysia Under-16s': 613,
 'Kabul Province': 614,
 'Warriors': 615,
 'Ireland Under-17s Women': 616,
 'Worcestershire Academy': 617,
 'Nooristan Province Under-16s': 618,
 'Windward Islands Under-19s': 619,
 'Thurstan College': 620,
 'Mannar-Vavuniya Combined Schools': 621,
 'Sri Lanka Board XI': 622,
 'Westerns': 623,
 'Yorkshire Under-14s': 624,
 'Marylebone Cricket Club Universities': 625,
 'Habib Bank Limited': 626,
 'Sri Lanka Navy Sports Club': 627,
 'Karachi Dolphins': 628,
 'Otago Under-21s Women': 629,
 'New South Wales Women': 630,
 'New South Wales Second XI': 631,
 'Zimbabwe Under-19s': 632,
 'Haryana': 633,
 'Saurashtra': 634,
 'Lincolnshire Under-15s': 635,
 'Kent 2nd XI': 636,
 'Madhya Pradesh Under-14s': 637,
 'Scotland Under-15s': 638,
 'Air India': 639,
 'Park-N-Shop': 640,
 'Multan': 641,
 'Netherlands': 642,
 'England Cricket Board Development Womens XI': 643,
 'Lancashire Cricket Board': 644,
 'Westville Boys High School': 645,
 'ICL World XI': 646,
 'Southern Express': 647,
 'Kandahar Province': 648,
 'Cape Cobras': 649,
 'Cricket Australia XI': 650,
 'Durham MCCU': 651,
 'Queensland': 652,
 'Afghanistan': 653,
 'Kandurata': 654,
 'Pushpadana Ladies': 655,
 'Australia Under-17s': 656,
 'Eastern Province Ladies': 657,
 'India Red': 658,
 'Baroda Under-19s': 659,
 'Vidarbha Women': 660,
 'India Blue Women': 661,
 'Dhaka Metro Under-18s': 662,
 'Border Under-13s': 663,
 'Uttar Pradesh Women': 664,
 'Army': 665,
 'Grenada Women': 666,
 'FOG-Seenigama': 667,
 'Northumberland Women': 668,
 'Dhaka Warriors': 669,
 'Gujranwala Cricket Association': 670,
 'ICL Pakistan XI': 671,
 'Gloucestershire Women': 672,
 'Knights': 673,
 'South Africa Colts XI': 674,
 'Peshawar': 675,
 'Arenco IT': 676,
 'India A': 677,
 'Antigua and Barbuda': 678,
 'Otago': 679,
 'Central Districts Women': 680,
 'Arunachal Pradesh': 681,
 'Northerns Under-17s': 682,
 'Worcestershire 2nd XI': 683,
 'Warwickshire': 684,
 'St Lucia': 685,
 'Sheikhupura Cricket Association': 686,
 'Barisal Division Under-16s': 687,
 'St. Peters College': 688,
 'Saracens Sports Club': 689,
 'Lahore Whites': 690,
 'Hyderabad Under-22s': 691,
 'Western Australia Under-23s': 692,
 'Grey High School': 693,
 'Perak': 694,
 'Odisha': 695,
 'Somerset 2nd XI': 696,
 'Chhattisgarh': 697,
 'Southern Ladies Cricket Club': 698,
 'Diamonds': 699,
 'Tripura Under-19s': 700,
 'Surrey Under-14s': 701,
 'Combined Provinces': 702,
 'Sylhet Divison Under-18s': 703,
 'Delhi': 704,
 'Nepal': 705,

In [22]:
players = []
count = 0
for index, row in tqdm(required_players.iterrows()):
    
    # If player doesnt have a proper team skip
    if type(row["Major teams"]) is not str:
        continue
        
    player = {}
    player["player_name"] = row["NAME"]
    player["player_full_name"] = row["Full name"]
    player["batting_style"] = row["Batting style"]
    player["bowling_style"] = row["Bowling style"]
    player["birthdate"] = row["Birthdate"]
    player["country_id"] = country_id_map[row["COUNTRY"]]
    
    team_list_ids = ""
    for team in get_clean_teams(row["Major teams"]):
        if team in team_id_map:
            team_list_ids += str(team_id_map[team]) + ","
    # removing last comma
    team_list_ids = team_list_ids[:-1]
    
    player["list_team_ids"] = team_list_ids
    players.append(player)

34016it [00:03, 11296.70it/s]

In [25]:
player_columns = ["player_id", "player_display_name", "player_name", "player_full_name", "batting_style", "bowling_style", "birthdate", "country_id"]
player_csv = pd.DataFrame(columns = player_columns)
for i in tqdm(range(len(players))):
    player_id = i+1
    player_display_name = "" # This needs to be updated later with fuzzy matching
    player_name = players[i]["player_name"]
    player_full_name = players[i]["player_full_name"]
    batting_style = players[i]["batting_style"]
    bowling_style = players[i]["bowling_style"]
    birthdate = players[i]["birthdate"]
    country_id = players[i]["country_id"]
    list_team_ids = players[i]["list_team_ids"]
    player_csv = player_csv.append({"player_id" : player_id, 
                                      "player_display_name" : player_display_name,
                                      "player_name" : player_name,
                                      "player_full_name" : player_full_name,
                                      "batting_style" : batting_style,
                                      "bowling_style" : bowling_style,
                                      "birthdate" : birthdate,
                                      "country_id" : country_id,
                                      "list_team_ids" : list_team_ids
                                     }, ignore_index=True)

100%|███████████████████████████████████████████████████████████████████████████| 32870/32870 [04:01<00:00, 136.29it/s]

In [30]:
player_csv[player_csv.player_name.str.contains("Kohli", na=False)]

,player_id,player_display_name,player_name,player_full_name,batting_style,bowling_style,birthdate,country_id,list_team_ids
4748,4749,,Somesh Kohli,Somesh K Kohli,NaN,NaN,06/05/86,16,"642,451,1067,937"
9513,9514,,Virat Kohli,Virat Kohli,Right-hand bat,Right-arm medium,05/11/88,2,"1035,704,658,92,1186"
9514,9515,,Taruwar Kohli,Taruwar Sushil Kohli,Right-hand bat,Right-arm medium,17/12/88,2,"92,262,232,445"
9515,9516,,Parth Kohli,Parth Sachin Kohli,Right-hand bat,Legbreak googly,09/08/96,2,"435,659,755"
9536,9537,,Akanksha Kohli,Akanksha Kohli,Right-hand bat,Right-arm medium-fast,13/08/89,2,384

In [32]:
player_csv.to_csv(os.path.join(clean_data_path, "player.csv"), index=False)